### ISSUE TITLE
Refactor thunks out of Store

### ISSUE THREAD

**Issue by AmaranthineCodices** [Roblox/rodux#14]
This depends on #5 (and #13 or an equivalent). We should refactor thunks out of the core `dispatch` method and move them to a middleware (how redux-thunk works). This middleware should probably be bundled by default, since thunks were implemented in Rodux before.

**Comment by LPGhatguy** [comment]
Should that middleware be enabled by default?

I'm not 100% confident that thunks are the best way to go about asynchronous tasks, so letting them be optional seems like a good idea.

**Comment by AmaranthineCodices** [comment]
I'd include them in Rodux, but not enable them by default. If people want thunks, they can enable the middleware themselves, but I don't see a need to enable them as-is.
