### ISSUE TITLE
Switch dependencies to Git submodules

### ISSUE THREAD

**Issue by LPGhatguy** [Roblox/rodux#19]
Right now, TestEZ and Lemur are loaded with this awful Lua-shell hybrid script in `bin`.

I'd really like to get rid of that script in favor of just using Git submodules.

**Comment by AmaranthineCodices** [comment]
This looks like it's done as of 9705a0ddf9df3734283cf4aeda34268a849069f8?

**Comment by LPGhatguy** [comment]
Oops, I always forget to add the "closes #xx" stuff to my commit messages.
