### ISSUE TITLE
Include instructions for setting up automated testing or running tests

### ISSUE THREAD

**Issue by Quenty** [Roblox/rodux#21]
Right now it's unclear how to run the tests or verify the project is working locally.

**Comment by LPGhatguy** [comment]
Hah, when I wrote the section for testing it was kind of up in the air how tests were going to be run, now it's pretty concrete:

* Run `lua bin/install-dependencies.lua` from the root (will be replaced by Git submodules)
* Run `lua spec.lua`

**Comment by LPGhatguy** [comment]
I think that this doc (which is kind of out of date) covers this case:

https://github.com/Roblox/rodux/blob/master/CONTRIBUTING.md#working-on-rodux
