### ISSUE TITLE
PascalCase compatibility layer

### ISSUE THREAD

**Issue by LPGhatguy** [Roblox/rodux#22]
We have some code at Roblox that uses an older version of Rodux (and Roact-Rodux) that has a PascalCase API. Before Rodux went public on GitHub, I changed that API, but that means that we haven't had the latest changes!

Should we introduce a (semi-private) PascalCase compatibility shim to the open source version of the library, or just monkeypatch methods only in the Roblox codebase?

**Comment by AmaranthineCodices** [comment]
Theoretically, you can do something like this:

```lua
local function pascalCaseifyStore(store)
    store.Dispatch = store.dispatch
    store.Subscribe = store.subscribe
    -- ...and so forth
end
```

Unless the method signatures are different?

I don't know that it makes sense to add a first-party compatibility shim to Rodux to support what is, effectively, legacy code. That seems like a maintenance burden.

**Comment by LPGhatguy** [comment]
I built the layer internally and it works well!

I had to do a little bit of hackery to patch the signal implementation that Rodux ships, which was not very fun.
