### ISSUE TITLE
loggerMiddleware should throw if given invalid arguments

### ISSUE THREAD

**Issue by AmaranthineCodices** [Roblox/rodux#24]
Since `loggerMiddleware` must be called before using it, there's a potential issue where if you *don't* call it, it's still a technically valid middleware...just one that silently eats all your actions. I ran into this issue on a personal project. It would be nice if `loggerMiddleware` errors if:

* It receives arguments of the wrong type
* It receives an invalid number of arguments

**Comment by LPGhatguy** [comment]
An alternative solution (used by some tests in Lemur now) would be to override `io.stdout.write` temporarily in the tests, which would allow `loggerMiddleware` to be used directly.

Is that configuration point useful for anything except tests?

**Comment by AmaranthineCodices** [comment]
No, not really. That would simplify things a great deal.

**Comment by LPGhatguy** [comment]
Agh, I tried to update `loggerMiddleware` to use that technique I talked about, but it makes the test not work inside Roblox itself! D:

**Comment by LPGhatguy** [comment]
I fixed this in 2026a1c.

I changed the internal `loggerMiddleware` function to expose a table with the actual middleware and an `outputFunction` field. In `init.lua`, I just expose the `middleware` field of that table, which lets tests override `outputFunction` without exposing it to the outside world.

I should've done this before the second prerelease, but I forgot >_<
