### ISSUE TITLE
Update docs to fix reducer page

### ISSUE THREAD

**Issue by jeparlefrancais** [Roblox/rodux#45]
There is still this on the [Reducer page](https://roblox.github.io/rodux/introduction/reducers/)
```lua
local reducer = function(action, state)
    return {
        myPhoneNumber = phoneNumberReducer(state.myPhoneNumber, action),
        myFriends = friendsReducer(state.myFriends, action),
    }
end
```

Where the action and state parameters are inverted. It's already fixed in the docs it's just not published online yet.

**Comment by ZoteTheMighty** [comment]
Deployed docs, should be fixed now
