### ISSUE TITLE
Update version and make new release or tag

### ISSUE THREAD

**Issue by Corecii** [Roblox/rodux#73]
Uplift has been publishing versions of Rodux and Roact to the Wally index for Roblox. Some users want updated versions of Rodux, but we're stuck because the Rodux version has not changed and we don't want to publish a conflicting version now.

Here are some options I discussed with some people:
1. We publish version `3.0.1`, which will conflict when Roblox officially releases that version (bad! I don't really consider this an option.)
2. We publish `3.0.1-ce63e3d` (or similar) which won't conflict with any version Roblox releases, but will require explicitly specifying in `wally.toml` since it's a prerelease tag version
3. You all update the Rodux version officially, then we publish with Wally.

Here's # 3! This would be the cleanest solution to give users an up-to-date version of Rodux. A new Release, Tag, or updating `rotriever.toml` with a new version is all we need to be confident that we can safely publish that version.

**Comment by Corecii** [comment]
I realize now that these changes are intentionally "unreleased" according to the changelog. From an external viewpoint, it's hard to keep track of how releases work with these open source modules since I've seen it suggested around that how releases are done isn't always consistent!

Sorry for the extra prodding then -- I'm just forwarding comments from Wally users and looking for solutions. I think now the best solution is either to wait for a release from you all or publish a prerelease version.

**Comment by Corecii** [comment]
Great, thank you!

> We'll also look to getting this release published to the Wally registry for community consumption as well

Uplift Games has been publishing these packages to Wally for you all. Would you like us to publish `4.0.0-rc.0` for you, or do you want to take on responsibility of publishing versions to Wally yourself? I can give you access to publish under `roblox` on the Wally registry if you want to start publishing it yourself!

**Comment by ratleypreston-cloud** [comment]
It sounds like the main issue is versioning and avoiding a conflicting Wally release while still giving users access to newer Rodux updates. I’d recommend resolving the package version strategy first and clearly documenting compatibility. The **[delta executor direct install ios](https://deltaiosexecutors.net/)** topic is separate from this dependency-management issue, so keeping the discussion focused on Rodux/Roact versioning should make the solution clearer.

**Comment by zauk482-lab** [comment]
That makes sense, and I appreciate the clarification about the intentionally unreleased changes. Release processes can definitely be confusing when different open-source modules follow inconsistent practices. Your effort to pass along Wally users’ feedback is helpful, especially when they are looking for practical solutions. Waiting for an official release or providing a prerelease version both seem reasonable approaches. Hopefully, [onetruque ](https://onetruco.com/)can also help users better understand upcoming changes.
